// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.Models.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Comment { get; set; }

    public string UserId { get; set; }

    public DateOnly CreateAt { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}