// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.Models.Models;

public partial class Order
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateOnly CreateAt { get; set; }

    public string UserId { get; set; }

    public double TotalPrice { get; set; }

    public bool Status { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}