// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.Models.Models;

public partial class PaymentMethod
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}